# Generated by Django 4.1.3 on 2023-05-08 11:18

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_shopowner_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='pinned_shops',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='social',
            field=models.CharField(max_length=2048),
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_pic', models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path)),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.shopowner')),
            ],
        ),
    ]
