# Generated by Django 4.1.3 on 2023-05-08 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_influencer_pinned_shops_alter_influencer_social_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='shop_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.shopowner'),
        ),
    ]
