# Generated by Django 4.1.3 on 2023-05-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_shops_shop_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='pinned_shops',
            field=models.CharField(default='[]', max_length=1024, null=True),
        ),
    ]
