# Generated by Django 4.1.3 on 2023-05-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_influencer_pinned_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
