# Generated by Django 4.1.3 on 2022-12-29 05:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Expired')], default=0)),
                ('referal_code', models.CharField(default=0, max_length=6)),
                ('payout', models.IntegerField(default=0)),
                ('validity', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.influencer')),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.shopowner')),
            ],
            options={
                'unique_together': {('shop_owner', 'influencer', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='ReferalEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('platform', models.IntegerField(choices=[(1, 'Instagram'), (2, 'WhatsApp'), (3, 'Facebook'), (4, 'Twitter'), (5, 'Snapchat'), (6, 'Other')])),
                ('bill_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('payout', models.IntegerField(validators=[django.core.validators.MinValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referal.connection')),
            ],
            options={
                'unique_together': {('referal', 'phone_number')},
            },
        ),
    ]
