# Generated by Django 4.1.3 on 2023-04-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_shopowner_profile_pic'),
        ('referal', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('shop_owner', 'influencer', 'current_status')},
        ),
    ]
